Allow banner config in site config
usnistgov/hugo-uswds pull request #22
Opened 2022-10-17 18:41 UTC by kylelaker

As-is, `usabanner` must be configured in each page's params (as does `draftbanner`) due to using `.Params.usabanner`. Using the `.Param` function instead allows looking up first at the page level and then in the site params. This will allow for enabling the banner globally and then (optionally) disabling it on select pages.

2023-01-06 18:13 UTC, david-waltermire-nist commented
@kylelaker Can you verify that the `Param` function is available in Hugo 0.83.1? If not, we will need to increment the required minimum version in [theme.yaml](https://github.com/usnistgov/hugo-uswds/blob/de41bce5a664ca42e5276815084b5f2de8cb9fba/theme.yaml#L8).

2023-01-06 18:14 UTC, david-waltermire-nist requested changes
Need to verify minimum required Hugo version.

2023-01-06 18:20 UTC, kylelaker commented
@david-waltermire-nist It looks like this was added (or at least available) in Hugo 0.18 (https://github.com/gohugoio/hugo/releases/tag/v0.18) with the Release Note item "Consolidate the Param methods". The commit associated with that was https://github.com/gohugoio/hugo/commit/58f31d2769ec63aa8dfd4eaad47703ce09b57a96 (included starting in v0.18) and describes the functionality of how `.Param` works.

2023-03-09 16:21 UTC, david-waltermire-nist approved these changes
Thanks!

2023-03-09 16:22 UTC, merged